produtos = {
    "dados": [
        {
            "partCode": "27001",
            "partType": "Product",
            "name": "Carne Burger",
            "quantity": 0,
            "defaultQuantity": 0,
            "observation": "",
            "unitPrice": 0,
            "addedUnitPrice": 0,
            "totalprice": 0,
            "items": []
        },
        {
            "partCode": "27002",
            "partType": "Product",
            "name": "Carne Whopper",
            "quantity": 1,
            "defaultQuantity": 1,
            "observation": "",
            "unitPrice": 0,
            "addedUnitPrice": 0,
            "totalprice": 0,
            "items": []
        },
        {
            "partCode": "27003",
            "partType": "Product",
            "name": "Carne T Grill",
            "quantity": 0,
            "defaultQuantity": 0,
            "observation": "",
            "unitPrice": 0,
            "addedUnitPrice": 0,
            "totalprice": 0,
            "items": []
        },
        {
            "partCode": "27004",
            "partType": "Product",
            "name": "Carne T Crispy",
            "quantity": 0,
            "defaultQuantity": 0,
            "observation": "",
            "unitPrice": 0,
            "addedUnitPrice": 0,
            "totalprice": 0,
            "items": []
        },
        {
            "partCode": "27005",
            "partType": "Product",
            "name": "Carne Chckn Sa",
            "quantity": 0,
            "defaultQuantity": 0,
            "observation": "",
            "unitPrice": 0,
            "addedUnitPrice": 0,
            "totalprice": 0,
            "items": []
        },
        {
            "partCode": "27006",
            "partType": "Product",
            "name": "Carne Crisp Ch",
            "quantity": 0,
            "defaultQuantity": 0,
            "observation": "",
            "unitPrice": 0,
            "addedUnitPrice": 0,
            "totalprice": 0,
            "items": []
        },
        {
            "partCode": "880012",
            "partType": "Product",
            "name": "Maionese Sabor Picles",
            "quantity": 0,
            "defaultQuantity": 0,
            "observation": "",
            "unitPrice": 0,
            "addedUnitPrice": 0,
            "totalprice": 0,
            "items": []
        },
        {
            "partCode": "5000076",
            "partType": "Product",
            "name": "Carne Picanha",
            "quantity": 0,
            "defaultQuantity": 0,
            "observation": "",
            "unitPrice": 0,
            "addedUnitPrice": 0,
            "totalprice": 0,
            "items": []
        },
        {
            "partCode": "8550011",
            "partType": "Product",
            "name": "Carne Veget",
            "quantity": 0,
            "defaultQuantity": 0,
            "observation": "",
            "unitPrice": 0,
            "addedUnitPrice": 0,
            "totalprice": 0,
            "items": []
        },
        {
            "partCode": "8700001",
            "partType": "Product",
            "name": "Maionese",
            "quantity": 1,
            "defaultQuantity": 1,
            "observation": "",
            "unitPrice": 0,
            "addedUnitPrice": 0,
            "totalprice": 0,
            "items": []
        },
        {
            "partCode": "8700002",
            "partType": "Product",
            "name": "Catchup",
            "quantity": 1,
            "defaultQuantity": 1,
            "observation": "",
            "unitPrice": 0,
            "addedUnitPrice": 0,
            "totalprice": 0,
            "items": []
        },
        {
            "partCode": "8700003",
            "partType": "Product",
            "name": "Mostarda",
            "quantity": 0,
            "defaultQuantity": 0,
            "observation": "",
            "unitPrice": 0,
            "addedUnitPrice": 0,
            "totalprice": 0,
            "items": []
        },
        {
            "partCode": "8700004",
            "partType": "Product",
            "name": "M Cheddar ",
            "quantity": 0,
            "defaultQuantity": 0,
            "observation": "",
            "unitPrice": 0,
            "addedUnitPrice": 0,
            "totalprice": 0,
            "items": []
        },
        {
            "partCode": "8700005",
            "partType": "Product",
            "name": "M BBQ Sand",
            "quantity": 0,
            "defaultQuantity": 0,
            "observation": "",
            "unitPrice": 0,
            "addedUnitPrice": 0,
            "totalprice": 0,
            "items": []
        },
        {
            "partCode": "8700006",
            "partType": "Product",
            "name": "M Furios Sand",
            "quantity": 0,
            "defaultQuantity": 0,
            "observation": "",
            "unitPrice": 0,
            "addedUnitPrice": 0,
            "totalprice": 0,
            "items": []
        },
        {
            "partCode": "8700007",
            "partType": "Product",
            "name": "Jalapeno",
            "quantity": 0,
            "defaultQuantity": 0,
            "observation": "",
            "unitPrice": 0,
            "addedUnitPrice": 0,
            "totalprice": 0,
            "items": []
        },
        {
            "partCode": "8700009",
            "partType": "Product",
            "name": "Molho Stacker",
            "quantity": 0,
            "defaultQuantity": 0,
            "observation": "",
            "unitPrice": 0,
            "addedUnitPrice": 0,
            "totalprice": 0,
            "items": []
        },
        {
            "partCode": "8700010",
            "partType": "Product",
            "name": "Picles ",
            "quantity": 1,
            "defaultQuantity": 1,
            "observation": "",
            "unitPrice": 0,
            "addedUnitPrice": 0,
            "totalprice": 0,
            "items": []
        },
        {
            "partCode": "8700011",
            "partType": "Product",
            "name": "Tomate",
            "quantity": 1,
            "defaultQuantity": 1,
            "observation": "",
            "unitPrice": 0,
            "addedUnitPrice": 0,
            "totalprice": 0,
            "items": []
        },
        {
            "partCode": "8700012",
            "partType": "Product",
            "name": "Alface ",
            "quantity": 1,
            "defaultQuantity": 1,
            "observation": "",
            "unitPrice": 0,
            "addedUnitPrice": 0,
            "totalprice": 0,
            "items": []
        },
        {
            "partCode": "8700013",
            "partType": "Product",
            "name": "Cebola",
            "quantity": 1,
            "defaultQuantity": 1,
            "observation": "",
            "unitPrice": 0,
            "addedUnitPrice": 0,
            "totalprice": 0,
            "items": []
        },
        {
            "partCode": "8700014",
            "partType": "Product",
            "name": "Cebola Furios",
            "quantity": 0,
            "defaultQuantity": 0,
            "observation": "",
            "unitPrice": 0,
            "addedUnitPrice": 0,
            "totalprice": 0,
            "items": []
        },
        {
            "partCode": "8700015",
            "partType": "Product",
            "name": "Crisp Onion",
            "quantity": 0,
            "defaultQuantity": 0,
            "observation": "",
            "unitPrice": 0,
            "addedUnitPrice": 0,
            "totalprice": 0,
            "items": []
        },
        {
            "partCode": "8700016",
            "partType": "Product",
            "name": "Cebola Shoyo",
            "quantity": 0,
            "defaultQuantity": 0,
            "observation": "",
            "unitPrice": 0,
            "addedUnitPrice": 0,
            "totalprice": 0,
            "items": []
        },
        {
            "partCode": "8700017",
            "partType": "Product",
            "name": "Queijo",
            "quantity": 1,
            "defaultQuantity": 1,
            "observation": "",
            "unitPrice": 0,
            "addedUnitPrice": 0,
            "totalprice": 0,
            "items": []
        },
        {
            "partCode": "8700018",
            "partType": "Product",
            "name": "Molho Especial",
            "quantity": 0,
            "defaultQuantity": 0,
            "observation": "",
            "unitPrice": 0,
            "addedUnitPrice": 0,
            "totalprice": 0,
            "items": []
        },
        {
            "partCode": "8700019",
            "partType": "Product",
            "name": "Onion Ring",
            "quantity": 0,
            "defaultQuantity": 0,
            "observation": "",
            "unitPrice": 0,
            "addedUnitPrice": 0,
            "totalprice": 0,
            "items": []
        },
        {
            "partCode": "8700020",
            "partType": "Product",
            "name": "Bacon",
            "quantity": 0,
            "defaultQuantity": 0,
            "observation": "",
            "unitPrice": 0,
            "addedUnitPrice": 0,
            "totalprice": 0,
            "items": []
        },
        {
            "partCode": "8700021",
            "partType": "Product",
            "name": "Molho A1",
            "quantity": 0,
            "defaultQuantity": 0,
            "observation": "",
            "unitPrice": 0,
            "addedUnitPrice": 0,
            "totalprice": 0,
            "items": []
        },
        {
            "partCode": "8700026",
            "partType": "Product",
            "name": "Molho Mafioso",
            "quantity": 0,
            "defaultQuantity": 0,
            "observation": "",
            "unitPrice": 0,
            "addedUnitPrice": 0,
            "totalprice": 0,
            "items": []
        },
        {
            "partCode": "8700027",
            "partType": "Product",
            "name": "Carne PEQ",
            "quantity": 0,
            "defaultQuantity": 0,
            "observation": "",
            "unitPrice": 0,
            "addedUnitPrice": 0,
            "totalprice": 0,
            "items": []
        },
        {
            "partCode": "8700041",
            "partType": "Product",
            "name": "Queijo Suico",
            "quantity": 0,
            "defaultQuantity": 0,
            "observation": "",
            "unitPrice": 0,
            "addedUnitPrice": 0,
            "totalprice": 0,
            "items": []
        },
        {
            "partCode": "8700042",
            "partType": "Product",
            "name": "Maionese Bacon",
            "quantity": 0,
            "defaultQuantity": 0,
            "observation": "",
            "unitPrice": 0,
            "addedUnitPrice": 0,
            "totalprice": 0,
            "items": []
        },
        {
            "partCode": "8800011",
            "partType": "Product",
            "name": "Catupiry",
            "quantity": 0,
            "defaultQuantity": 0,
            "observation": "",
            "unitPrice": 0,
            "addedUnitPrice": 0,
            "totalprice": 0,
            "items": []
        }
    ]
}
